version: '3.8'

services:
  # 数据库服务 - 需要持续运行
  mongodb:
    image: mongo:7
    restart: unless-stopped
    container_name: ezboard-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./docker/mongo-init:/docker-entrypoint-initdb.d
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME:-admin}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD:-password}
      - MONGO_INITDB_DATABASE=${MONGO_DB_NAME:-ezboard}
    networks:
      - app-network

  # 后端应用服务 - 需要持续运行
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: ezboard-backend
    ports:
      - "5055:5055"
    depends_on:
      - mongodb
    environment:
      - NODE_ENV=production
      - DATABASE_URL=mongodb://mongodb:27017/${MONGO_DB_NAME:-ezboard}
      - PORT=5055
    volumes:
      - ./server/.env.production:/app/server/.env.production:ro
    networks:
      - app-network

  # Nginx 反向代理 - 需要持续运行
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    container_name: ezboard-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./docker/ssl:/etc/nginx/ssl:ro  # SSL证书目录
      - nginx_logs:/var/log/nginx
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  mongodb_data:
    driver: local
  nginx_logs:
    driver: local

networks:
  app-network:
    driver: bridge 